// Generated by CoffeeScript 1.4.0

/*
 facebook connect
*/


(function() {
  var FBConnect;

  FBConnect = (function() {

    function FBConnect() {
      this.logined = false;
      this.config = require('./config.json');
    }

    FBConnect.prototype.is_login = function(cb) {
      return cb(this.logined);
    };

    FBConnect.prototype.login = function(cb) {
      console.log("Login server is ready. So go " + (this.login_url()));
      return cb(null);
    };

    FBConnect.prototype.instruct_login = function(cb) {
      console.log("Fisrt, you should login with Facebook. Go to " + (this.login_url()));
      return cb(null);
    };

    FBConnect.prototype.login_url = function() {
      return "http://" + this.config.http_server_host + ":" + this.config.http_server_port + "/";
    };

    FBConnect.prototype.set_access_token = function(accesss_token) {
      FB.setAccessToken(accesss_token);
      return this.logined = true;
    };

    return FBConnect;

  })();

  module.exports = FBConnect;

}).call(this);
