// Generated by CoffeeScript 1.4.0

/*
 STDIN and STDOUT simulator for web demo.
*/


(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  facebook_terminal.STDIN = (function() {

    function STDIN(cb) {
      this.input = __bind(this.input, this);

    }

    STDIN.prototype.input = function(value) {
      return this.callback(value);
    };

    STDIN.prototype.setCallback = function(cb) {
      return this.callback = cb;
    };

    return STDIN;

  })();

  facebook_terminal.STDOUT = (function() {

    function STDOUT(callback) {
      this.callback = callback;
    }

    STDOUT.prototype.write = function(value) {
      if (value !== void 0) {
        return this.callback(value);
      }
    };

    return STDOUT;

  })();

}).call(this);
