// Generated by CoffeeScript 1.4.0

/*
 facebook connect for web demo
*/


(function() {

  facebook_terminal.WebFBConnect = (function() {

    function WebFBConnect() {
      this.logined = null;
    }

    WebFBConnect.prototype.is_login = function(cb) {
      var _this = this;
      if (this.logined === null) {
        console.log("checking your login status...");
        return FB.getLoginStatus(function(response) {
          if (response.status === 'connected') {
            _this.uid = response.authResponse.userID;
            _this.accessToken = response.authResponse.accessToken;
            console.log("You've been logged in.");
            _this.logined = true;
            return cb(true);
          } else if (response.status === 'not_authorized') {
            console.log("You haven't been logged in yet.");
            _this.logined = false;
            return cb(false);
          } else {
            console.log("You haven't been logged in yet.");
            _this.logined = false;
            return cb(false);
          }
        });
      } else {
        return cb(this.logined);
      }
    };

    WebFBConnect.prototype.login = function(cb) {
      var _this = this;
      return FB.login(function(response) {
        if (response.authResponse) {
          return FB.api('/me', function(response) {
            console.log("You've been logged in.");
            console.log('Hi, ' + response.name + '.');
            _this.logined = true;
            return cb(null);
          });
        } else {
          return _this.instruct_login(cb);
        }
      });
    };

    WebFBConnect.prototype.permission = function(permissions, cb) {
      var _this = this;
      return FB.login(function(response) {
        if (response.authResponse) {
          console.log("I've got the permission" + (permissions.length > 1 ? 's' : '') + ": " + (permissions.join(',')));
          return cb();
        } else {
          console.log("Is anything wrong?");
          return cb();
        }
      }, {
        scope: permissions.join(',')
      });
    };

    WebFBConnect.prototype.instruct_login = function(cb) {
      console.log("To start this demo, you should login with Facebook. Type 'login'");
      console.log("(I'm never gonna post anything without asking)");
      return cb(null);
    };

    return WebFBConnect;

  })();

}).call(this);
